name: ML Model CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    
    - name: Train model
      run: |
        python src/train.py
    
    - name: Test model
      run: |
        python test_model.py
    
    - name: Archive model artifacts
      uses: actions/upload-artifact@v2
      with:
        name: model-artifacts
        path: src/trained_model.joblib
    
    - name: Deploy model
      run: |
        echo "Deploying model..."
        # Add actual deployment steps here
