name: ML Model CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest scikit-learn
    
    - name: Lint with flake8
      run: |
        flake8 .
    
    - name: Run tests
      run: |
        pytest tests/
    
    - name: Train model
      run: |
        python train_model.py
    
    - name: Deploy model
      run: |
        python deploy_model.py
